<?php
namespace Tests\Feature\B3;
use App\Models\User;use Illuminate\Support\Facades\DB;use Tests\Support\CreatesFactoryFlowSchema;use Tests\TestCase;
class CutReelTest extends TestCase
{
 use CreatesFactoryFlowSchema;
 protected function setUp():void{parent::setUp();$this->createFactoryFlowSchema();DB::table('users')->insert(['user_id'=>1,'username'=>'worker','password_hash'=>'x','is_active'=>1]);DB::table('DanhSachMaSP')->insert(['id'=>1,'Ten'=>'SP','Ma'=>'SP']);DB::table('TTThanhPham')->insert(['id'=>10,'DanhSachSP_ID'=>1,'MaBin'=>'MB001','NhapKho'=>1,'Temp'=>0]);DB::table('TTNhapKhoTP')->insert(['id'=>20,'TTThanhPham_ID'=>10,'TenSP'=>'SP','TongChieuDai'=>100,'GhiChu'=>'','NguoiLam'=>'u','NgayNhapKho'=>'2026-01-01','DateInsert'=>'2026-01-01']);DB::table('TTCuonDay')->insert(['id'=>30,'SoCuon'=>1,'ChieuDai_1cuon'=>100,'ThongTinNhapKho_ID'=>20,'Ngay'=>'2026-01-01']);DB::table('KeHoach')->insert(['id'=>1,'MaKeHoach'=>'KH','NgayKeHoach'=>'2026-10-01','TrangThai'=>'ACTIVE']);DB::table('KeHoachHang')->insert(['id'=>40,'KeHoach_ID'=>1,'DanhSachMaSP_ID'=>1,'SoLuongCuonCanLay'=>0,'ChieuDai1Cuon_KeHoach'=>100]);DB::table('KeHoachCatNhom')->insert(['id'=>50,'KeHoachHang_ID'=>40]);DB::table('KeHoachCatChiTiet')->insert([['id'=>60,'KeHoachCatNhom_ID'=>50,'ChieuDaiCanCat'=>40],['id'=>61,'KeHoachCatNhom_ID'=>50,'ChieuDaiCanCat'=>20]]);}
 private function u():User{return User::query()->findOrFail(1);}
 public function test_first_cut_creates_and_binds_partial_then_second_scan_continues_partial():void{$raw='cuontp;MB001;QR-A';$this->actingAs($this->u())->postJson('/api/b3/execute/cut',['raw_qr'=>$raw,'ke_hoach_id'=>1,'ke_hoach_hang_id'=>40,'group_id'=>50,'detail_id'=>60,'end_value'=>100,'direction'=>1,'operation_token'=>'11111111-1111-4111-8111-111111111111'])->assertOk();$partial=DB::table('TonCuonLe')->first();$this->assertSame($raw,$partial->MaCuon);$this->assertSame(0,(int)$partial->SoDau);$this->assertSame(60,(int)$partial->SoCuoi);$this->assertSame((int)$partial->id,(int)DB::table('KeHoachCatNhom')->where('id',50)->value('TonCuonLe_ID'));$this->assertDatabaseHas('LichSuCat',['KeHoachCatChiTiet_ID'=>60,'LoaiNguon'=>'CUON_CHAN','MaQuetThucTe'=>$raw]);$this->actingAs($this->u())->postJson('/api/b3/execute/cut',['raw_qr'=>$raw,'ke_hoach_id'=>1,'ke_hoach_hang_id'=>40,'group_id'=>50,'detail_id'=>61,'operation_token'=>'22222222-2222-4222-8222-222222222222'])->assertOk();$this->assertDatabaseHas('TonCuonLe',['id'=>$partial->id,'SoDau'=>0,'SoCuoi'=>40,'TrangThai'=>'ACTIVE']);$this->assertDatabaseHas('LichSuCat',['KeHoachCatChiTiet_ID'=>61,'LoaiNguon'=>'CUON_LE']);}
 public function test_cut_rejects_item_from_different_selected_plan():void{DB::table('KeHoach')->insert(['id'=>2,'MaKeHoach'=>'KH2','NgayKeHoach'=>'2026-10-02','TrangThai'=>'ACTIVE']);DB::table('KeHoachHang')->insert(['id'=>41,'KeHoach_ID'=>2,'DanhSachMaSP_ID'=>1,'SoLuongCuonCanLay'=>0,'ChieuDai1Cuon_KeHoach'=>100]);DB::table('KeHoachCatNhom')->insert(['id'=>51,'KeHoachHang_ID'=>41]);DB::table('KeHoachCatChiTiet')->insert(['id'=>62,'KeHoachCatNhom_ID'=>51,'ChieuDaiCanCat'=>20]);$this->actingAs($this->u())->postJson('/api/b3/execute/cut',['raw_qr'=>'cuontp;MB001;QR-B','ke_hoach_id'=>1,'ke_hoach_hang_id'=>41,'group_id'=>51,'detail_id'=>62,'end_value'=>100,'direction'=>1,'operation_token'=>'33333333-3333-4333-8333-333333333333'])->assertStatus(409)->assertJsonPath('error_code','STALE_DATA');$this->assertSame(0,DB::table('LichSuCat')->count());$this->assertSame(0,DB::table('TonCuonLe')->count());}

}
