<?php
namespace Tests\Feature\B3;
use App\Models\User;use Illuminate\Support\Facades\DB;use Tests\Support\CreatesFactoryFlowSchema;use Tests\TestCase;
class TakeWholeReelTest extends TestCase
{
 use CreatesFactoryFlowSchema;
 protected function setUp():void{parent::setUp();$this->createFactoryFlowSchema();DB::table('users')->insert(['user_id'=>1,'username'=>'worker','password_hash'=>'x','is_active'=>1]);DB::table('DanhSachMaSP')->insert(['id'=>1,'Ten'=>'SP','Ma'=>'SP']);DB::table('TTThanhPham')->insert([['id'=>10,'DanhSachSP_ID'=>1,'MaBin'=>'OLD','NhapKho'=>1,'Temp'=>0],['id'=>11,'DanhSachSP_ID'=>1,'MaBin'=>'SCAN','NhapKho'=>1,'Temp'=>0]]);DB::table('TTNhapKhoTP')->insert([['id'=>20,'TTThanhPham_ID'=>10,'TenSP'=>'SP','TongChieuDai'=>100,'GhiChu'=>'','NguoiLam'=>'u','NgayNhapKho'=>'2026-01-01','DateInsert'=>'2026-01-01'],['id'=>21,'TTThanhPham_ID'=>11,'TenSP'=>'SP','TongChieuDai'=>100,'GhiChu'=>'','NguoiLam'=>'u','NgayNhapKho'=>'2026-02-01','DateInsert'=>'2026-02-01']]);DB::table('TTCuonDay')->insert([['id'=>30,'SoCuon'=>1,'ChieuDai_1cuon'=>100,'ThongTinNhapKho_ID'=>20,'Ngay'=>'2026-01-01'],['id'=>31,'SoCuon'=>1,'ChieuDai_1cuon'=>100,'ThongTinNhapKho_ID'=>21,'Ngay'=>'2026-02-01']]);DB::table('KeHoach')->insert(['id'=>1,'MaKeHoach'=>'KH','NgayKeHoach'=>'2026-10-01','TrangThai'=>'ACTIVE']);DB::table('KeHoachHang')->insert(['id'=>40,'KeHoach_ID'=>1,'DanhSachMaSP_ID'=>1,'SoLuongCuonCanLay'=>1,'ChieuDai1Cuon_KeHoach'=>100]);}
 private function u():User{return User::query()->findOrFail(1);}
 public function test_take_one_uses_fifo_across_product_and_authenticated_username():void{$token='11111111-1111-4111-8111-111111111111';$this->actingAs($this->u())->postJson('/api/b3/execute/take-whole',['raw_qr'=>'cuontp;SCAN;QR-A','ke_hoach_id'=>1,'ke_hoach_hang_id'=>40,'operation_token'=>$token])->assertOk();$this->assertDatabaseHas('LichSuLayCuon',['KeHoachHang_ID'=>40,'TTCuonDay_ID'=>30,'SoLuong'=>1,'NguoiThucHien'=>'worker']);$this->actingAs($this->u())->postJson('/api/b3/execute/take-whole',['raw_qr'=>'cuontp;SCAN;QR-A','ke_hoach_id'=>1,'ke_hoach_hang_id'=>40,'operation_token'=>$token])->assertStatus(409)->assertJsonPath('error_code','DUPLICATE_REQUEST');$this->assertSame(1,DB::table('LichSuLayCuon')->count());}
 public function test_take_whole_rejects_item_from_different_selected_plan():void{DB::table('KeHoach')->insert(['id'=>2,'MaKeHoach'=>'KH2','NgayKeHoach'=>'2026-10-02','TrangThai'=>'ACTIVE']);DB::table('KeHoachHang')->insert(['id'=>41,'KeHoach_ID'=>2,'DanhSachMaSP_ID'=>1,'SoLuongCuonCanLay'=>1,'ChieuDai1Cuon_KeHoach'=>100]);$this->actingAs($this->u())->postJson('/api/b3/execute/take-whole',['raw_qr'=>'cuontp;SCAN;QR-B','ke_hoach_id'=>1,'ke_hoach_hang_id'=>41,'operation_token'=>'22222222-2222-4222-8222-222222222222'])->assertStatus(409)->assertJsonPath('error_code','STALE_DATA');$this->assertSame(0,DB::table('LichSuLayCuon')->count());}

}
